<html>
<head>
<title>TestNG:  Backend Services</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Backend Services</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>13/1/1</td>
</tr><tr>
<td>Started on:</td><td>Thu Jul 18 14:46:47 GMT+05:30 2019</td>
</tr>
<tr><td>Total time:</td><td>0 seconds (101 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='retry_fail_cases.TestNGRetryFailDemo.test3()'><b>test3</b><br>Test class: retry_fail_cases.TestNGRetryFailDemo</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at retry_fail_cases.TestNGRetryFailDemo.test3(TestNGRetryFailDemo.java:22)
... Removed 29 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1018298342", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1018298342'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at retry_fail_cases.TestNGRetryFailDemo.test3(TestNGRetryFailDemo.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>retry_fail_cases.TestNGRetryFailDemo@1ce92674</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='grouping.TestNGGroupDemo.test1()'><b>test1</b><br>Test class: grouping.TestNGGroupDemo</td>
<td></td>
<td>0</td>
<td>grouping.TestNGGroupDemo@3fee9989</td></tr>
<tr>
<td title='listeners.TestNGListenerDemo.test1()'><b>test1</b><br>Test class: listeners.TestNGListenerDemo</td>
<td></td>
<td>0</td>
<td>listeners.TestNGListenerDemo@73ad2d6</td></tr>
<tr>
<td title='retry_fail_cases.TestNGRetryFailDemo.test1()'><b>test1</b><br>Test class: retry_fail_cases.TestNGRetryFailDemo</td>
<td></td>
<td>0</td>
<td>retry_fail_cases.TestNGRetryFailDemo@1ce92674</td></tr>
<tr>
<td title='grouping.TestNGGroupDemo.test2()'><b>test2</b><br>Test class: grouping.TestNGGroupDemo</td>
<td></td>
<td>0</td>
<td>grouping.TestNGGroupDemo@3fee9989</td></tr>
<tr>
<td title='listeners.TestNGListenerDemo.test2()'><b>test2</b><br>Test class: listeners.TestNGListenerDemo</td>
<td></td>
<td>0</td>
<td>listeners.TestNGListenerDemo@73ad2d6</td></tr>
<tr>
<td title='retry_fail_cases.TestNGRetryFailDemo.test2()'><b>test2</b><br>Test class: retry_fail_cases.TestNGRetryFailDemo</td>
<td></td>
<td>0</td>
<td>retry_fail_cases.TestNGRetryFailDemo@1ce92674</td></tr>
<tr>
<td title='grouping.TestNGGroupDemo.test3()'><b>test3</b><br>Test class: grouping.TestNGGroupDemo</td>
<td></td>
<td>0</td>
<td>grouping.TestNGGroupDemo@3fee9989</td></tr>
<tr>
<td title='listeners.TestNGListenerDemo.test3()'><b>test3</b><br>Test class: listeners.TestNGListenerDemo</td>
<td></td>
<td>0</td>
<td>listeners.TestNGListenerDemo@73ad2d6</td></tr>
<tr>
<td title='grouping.TestNGGroupDemo.test4()'><b>test4</b><br>Test class: grouping.TestNGGroupDemo</td>
<td></td>
<td>0</td>
<td>grouping.TestNGGroupDemo@3fee9989</td></tr>
<tr>
<td title='listeners.TestNGListenerDemo2.test4()'><b>test4</b><br>Test class: listeners.TestNGListenerDemo2</td>
<td></td>
<td>0</td>
<td>listeners.TestNGListenerDemo2@7085bdee</td></tr>
<tr>
<td title='grouping.TestNGGroupDemo.test5()'><b>test5</b><br>Test class: grouping.TestNGGroupDemo</td>
<td></td>
<td>0</td>
<td>grouping.TestNGGroupDemo@3fee9989</td></tr>
<tr>
<td title='listeners.TestNGListenerDemo2.test5()'><b>test5</b><br>Test class: listeners.TestNGListenerDemo2</td>
<td></td>
<td>0</td>
<td>listeners.TestNGListenerDemo2@7085bdee</td></tr>
<tr>
<td title='listeners.TestNGListenerDemo2.test6()'><b>test6</b><br>Test class: listeners.TestNGListenerDemo2</td>
<td></td>
<td>0</td>
<td>listeners.TestNGListenerDemo2@7085bdee</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-skipped'>
<tr><td colspan='4' align='center'><b>SKIPPED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='retry_fail_cases.TestNGRetryFailDemo.test3()'><b>test3</b><br>Test class: retry_fail_cases.TestNGRetryFailDemo</td>
<td><div><pre>java.lang.AssertionError: expected [true] but found [false]
	at retry_fail_cases.TestNGRetryFailDemo.test3(TestNGRetryFailDemo.java:22)
... Removed 29 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace2104545713", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace2104545713'><pre>java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at retry_fail_cases.TestNGRetryFailDemo.test3(TestNGRetryFailDemo.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
</pre></div></td>
<td>0</td>
<td>retry_fail_cases.TestNGRetryFailDemo@1ce92674</td></tr>
</table><p>
</body>
</html>